version: '3'
services:
  mongo:
    image: mongo:4.0.4
    container_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - /var/lib/docker/volumes/mongo-data:/data/db
    ports:
      - '27017:27017'
volumes:
  mongo:        
